name: CI

on:
  push:
    paths-ignore:
    - '**.md'
    - 'docs/*'
    - 'LICENSE'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup stack
      uses: mstksg/setup-stack@v1
    - name: Run tests
      run: stack test
